domains:
  - cuirass
php_version: "8.5"
node_version: "26"
framework: laravel
framework_version: "13"
secured: true
services:
  - mailpit
  - mysql-9-7:
      preset: mysql
      version: "9.7"
workers:
  - vite
